zuihou:
  mysql:
    ip: ${MYSQL_IP:127.0.0.1}
    port: 3306
    username: root
    password: root

xxl.job:
  executor:
    ip: ${EXECUTOR_IP:127.0.0.1}
    port: ${EXECUTOR_PORT:8771}

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${zuihou.mysql.ip}:${zuihou.mysql.port}/${zuihou.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull
